config/routes.rb
Askme::Application.routes.draw do
  root :to => "nerds#index"

  resources :nerds  
  resources :answers  #not sure how you want to do this as a nerd has a question and an answer.
 

end

app/models/nerd.rb
class Nerd < ActiveRecord::Base
  attr_accessible :answer, :nameA, :nameB, :question
  validates :question, presence: :true
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nerds_controller.rb
class NerdsController < ApplicationController
  # GET /nerds
  # GET /nerds.json
  def index
    @nerds = Nerd.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nerds }
    end
  end

  # GET /nerds/1
  # GET /nerds/1.json
  def show
    @nerd = Nerd.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nerd }
    end
  end

  # GET /nerds/new
  # GET /nerds/new.json
  def new
    @nerd = Nerd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nerd }
    end
  end

  # GET /nerds/1/edit
  def edit
    @nerd = Nerd.find(params[:id])
  end

  # POST /nerds
  # POST /nerds.json
  def create
    @nerd = Nerd.new(params[:nerd])

    respond_to do |format|
      if @nerd.save
        format.html { redirect_to @nerd, notice: 'Successfully created.' }
        format.json { render json: @nerd, status: :created, location: @nerd }
      else
        format.html { render action: "new" }
        format.json { render json: @nerd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nerds/1
  # PUT /nerds/1.json
  def update
    @nerd = Nerd.find(params[:id])

    respond_to do |format|
      if @nerd.update_attributes(params[:nerd])
        format.html { redirect_to @nerd, notice: 'Nerd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nerd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nerds/1
  # DELETE /nerds/1.json
  def destroy
    @nerd = Nerd.find(params[:id])
    @nerd.destroy

    respond_to do |format|
      format.html { redirect_to nerds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nerds_helper.rb
module NerdsHelper
end

app/views/answer/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <div class="field">
    <%= f.label :nameB %><br />
    <%= f.text_field :nameB %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/answer/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name B:</b>
  <%= @nerd.nameB %>
</p>

<p>
  <b>Answer:</b>
  <%= @nerd.answer %>
</p>


<%= link_to 'Edit', edit_nerd_path(@nerd) %> |
<%= link_to 'Back', nerds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ask Me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nerds/_form.html.erb
<%= form_for(@nerd) do |f| %>
  <% if @nerd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nerd.errors.count, "error") %> prohibited this nerd from being saved:</h2>

      <ul>
      <% @nerd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nameA, "Question Seeker"%>
    <%= f.text_field :nameA %>
  </div>
  <div class="field">
    <%= f.label :question, "Question" %><br />
    <%= f.text_area :question %>
  </div>

  <%= f.submit "Submit" %>
<% end %>

app/views/nerds/edit.html.erb
<h1>Editing nerd</h1>

<%= render 'form' %>

<%= link_to 'Show', @nerd %> |
<%= link_to 'Back', nerds_path %>

app/views/nerds/index.html.erb
<h1>Ask a question, answer a question</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Question Seeker</th>
    <th>Answer</th>
    <th>Contributor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nerds.each do |nerd| %>
  <tr>
    <td><%= nerd.question %></td>
    <td><%= nerd.nameA %></td>
    <% if nerd.answer.nil? %>
      <td><%= link_to "Submit Answer", answer_path %></td>
    <% else %>
      <td><%= nerd.answer %></td>
      <td><%= nerd.nameB %></td>
    <% end %>
    <td><%= link_to 'Show', nerd %></td>
    <td><%= link_to 'Edit', edit_nerd_path %></td>
    <td><%= link_to 'Destroy', nerd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_nerd_path %>

app/views/nerds/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', nerds_path %>

app/views/nerds/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Question Seeker:</b>
  <%= @nerd.nameA %>
</p>

<p>
  <b>Question:</b>
  <%= @nerd.question %>
</p>

<%= link_to 'Edit', edit_nerd_path %> |
<%= link_to 'Back', nerds_path %>

<%= link_to "Submit Answer", new_answer_path %>